#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["kubertest3api.csproj", "kubertest3api/"]
RUN dotnet restore "kubertest3api/kubertest3api.csproj"
WORKDIR "/src/kubertest3api"
COPY . .
RUN dotnet build "kubertest3api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "kubertest3api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "kubertest3api.dll"]