apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 3
  selector:
    matchLabels:
      api: weatherforecast
  template:
    metadata:
      labels:
        api: weatherforecast
    spec:
      containers:
      - name: kubertest3api
        image: siresin/kubertest3api