version: '3'

services:
  db_auth:
    container_name: db_auth
    ports:
       - "5438:5432"
    environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=admin
    image: postgres:alpine3.17
    volumes:
        - type: volume
          source: pgdbdata
          target: /var/lib/postgresql/data
        
            
volumes:
  pgdbdata: null
